version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/app
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/install.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: ubuntu
